# Assignment 5, Problem 2
### Cynthia Cho

I have not given or received any unauthorized assistance on this assignment.

Note:  Instead of printing the final board, each generation (iteration) is printed to see how the board progresses through the game all the way up till the last generation, which is the final board.

In [2]:
## importing numpy
import numpy as np
import matplotlib.pyplot as plt 
#mport matplotlib as cm
import random
#import math

Rules to Conway's Game of Life:

• Rule 1: Any live cell (marked as 1) with fewer than two live neighbors dies, as if by underpopulation.

• Rule 2: Any live cell (marked as 1) with two or three live neighbors lives on to the next generation.

• Rule 3: Any live cell (marked as 1) with more than three live neighbors dies, as if by overpopulation.

• RUle 4: Any dead cell (marked as 0) with exactly three live neighbors becomes a live cell, as if by reproduction.

In [3]:
## Write a function called conway(s, p) that generates a board, which is a square two dimensional NumPy array of size s.
## If p is set to 1, all cells should be 1 (alive).  Start with p=0.1; about 10 percent of cells should 1.

def conway(s, p):
    ''' return a board of dimension 's' and the 1's are populated with a probability of p '''
    
    weights = [p, 1-p]  ## weights used for populating 1's and 0's.  1 = alive, 0 = dead
    board = np.random.choice([1,0], s*s, p=weights).reshape(s,s)  # random.choice allows for range of values, dimension, 
    return board  ## returns board of s dimension

In [5]:
## Write a function advance(b,t) that accepts a Conway board and advances it t time steps according to the rules:

def advance(b, t):
    ''' function plays Conway's Game of life 't' times '''
    
    for i in range( t):
        if i <= t:
            print("Generation:, ", i,'\n', b)  ## counts down and prints each iteration of the board as it changes
                                                ## generation count starts from 0
            print()
            rowDim, colDim = b.shape
            c = np.zeros((b.shape), dtype = np.int)  ## creates an empty board to populate with the changes as cells live and die

            for x in range(-1, rowDim-1):
                for y in range(-1, colDim-1):
                    new = np.array([b[x-1][y-1], b[x-1][y], b[x-1][y+1],
                                    b[x][y-1],   b[x][y],   b[x][y+1], 
                                    b[x+1][y-1], b[x+1][y], b[x+1][y+1]])
                    total = np.sum(new) - b[x,y]
                    if b[x, y] == 1:  ## if the cell is alive (1)
                        if total < 2 or total > 3:  ## surrounding total number of alive cells is less than 2 or greater than 3
                            c[x, y] = 0  ## satisfies rule 1 and rule 3
                        elif total == 2 or total == 3:  ## satisfies rule 2
                            c[x, y] = 1 

                    elif b[x, y] == 0:  ## satifies rule 4
                        if total == 3:
                            c[x, y] = 1
            b = c

Test call of Conway's Game of Life shown with iterations of each stage (Generation):

In [25]:
## s=5, p=0.25, t=5
b = conway(5,.25)
advance(b, 5)

Generation:,  0 
 [[0 1 1 0 1]
 [0 1 1 0 1]
 [0 1 0 0 0]
 [0 0 0 0 0]
 [0 0 1 0 0]]

Generation:,  1 
 [[0 0 0 0 0]
 [0 0 0 0 0]
 [1 1 1 0 0]
 [0 0 0 0 0]
 [0 1 1 1 0]]

Generation:,  2 
 [[0 0 1 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [1 0 0 1 0]
 [0 0 1 0 0]]

Generation:,  3 
 [[0 1 1 0 0]
 [0 1 1 0 0]
 [1 1 1 0 0]
 [0 1 1 0 0]
 [0 1 1 1 0]]

Generation:,  4 
 [[1 0 0 0 0]
 [0 0 0 1 0]
 [1 0 0 1 0]
 [0 0 0 0 0]
 [1 0 0 1 0]]



In [26]:
## s=7, p=0.25, t=20
b = conway(7,.25)
advance(b, 20)

Generation:,  0 
 [[0 0 0 0 0 1 0]
 [0 0 0 0 1 1 0]
 [0 1 0 1 0 0 0]
 [0 0 1 0 1 0 0]
 [0 1 0 0 1 1 0]
 [0 0 1 0 1 0 0]
 [1 1 0 1 0 1 0]]

Generation:,  1 
 [[0 0 0 0 0 1 0]
 [0 0 0 0 1 1 0]
 [0 0 1 1 0 1 0]
 [0 1 1 0 1 1 0]
 [0 1 1 0 1 1 0]
 [1 0 1 0 0 0 1]
 [0 1 1 1 0 1 1]]

Generation:,  2 
 [[0 0 1 1 0 0 0]
 [0 0 0 1 0 1 1]
 [0 1 1 0 0 0 1]
 [0 0 0 0 0 0 1]
 [0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0]
 [0 1 1 1 1 1 0]]

Generation:,  3 
 [[0 1 0 0 0 0 1]
 [1 1 0 1 1 1 1]
 [0 0 1 0 0 0 1]
 [1 0 0 0 0 1 0]
 [0 0 0 0 0 0 0]
 [0 0 1 0 0 1 0]
 [0 1 0 0 1 0 0]]

Generation:,  4 
 [[0 1 0 1 0 0 1]
 [0 1 0 1 1 0 0]
 [0 0 1 1 0 0 0]
 [0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0]
 [1 1 1 0 0 1 0]]

Generation:,  5 
 [[0 0 0 1 0 1 1]
 [1 1 0 0 1 0 0]
 [0 0 1 1 1 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [1 1 0 0 0 0 1]
 [1 1 1 0 0 0 1]]

Generation:,  6 
 [[0 0 0 1 1 1 0]
 [1 1 0 0 0 0 1]
 [0 1 1 1 1 0 0]
 [0 0 0 1 0 0 0]
 [1 0 0 0 0 0 0]
 [0 0 1 0 0 0 1]
 [0 0 1 0 0 0 0]]

Generation:,  7 
 [[1 1 1 1

In [27]:
## s=8, p=0.40, t=6
b = conway(8,0.40)
advance(b, 6)

Generation:,  0 
 [[1 1 1 1 0 1 0 1]
 [0 1 0 0 0 0 0 1]
 [0 1 0 0 1 1 0 1]
 [0 1 1 0 0 0 0 0]
 [1 0 0 0 0 1 1 0]
 [0 1 0 1 1 0 0 0]
 [0 0 0 1 0 0 1 0]
 [0 0 0 1 0 1 1 1]]

Generation:,  1 
 [[0 1 0 1 0 1 0 0]
 [0 0 0 1 0 1 0 1]
 [0 1 0 0 0 0 1 0]
 [0 1 1 0 1 0 0 1]
 [1 0 0 1 1 1 0 0]
 [0 0 1 1 1 0 1 1]
 [0 0 0 1 0 0 1 1]
 [0 1 0 1 0 1 0 0]]

Generation:,  2 
 [[1 0 0 1 0 1 0 0]
 [1 0 0 0 0 1 0 0]
 [0 1 0 1 1 1 1 1]
 [0 1 1 0 1 0 1 1]
 [1 0 0 0 0 0 0 0]
 [1 0 1 0 0 0 0 0]
 [1 0 0 0 0 0 0 1]
 [1 0 0 1 0 1 0 0]]

Generation:,  3 
 [[1 1 0 0 0 1 1 1]
 [1 1 1 1 0 0 0 0]
 [0 1 0 1 0 0 0 0]
 [0 1 1 0 1 0 0 0]
 [1 0 1 1 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 1]
 [1 1 0 0 0 0 1 0]]

Generation:,  4 
 [[0 0 0 0 0 1 1 0]
 [0 0 0 1 1 0 1 0]
 [0 0 0 0 1 0 0 0]
 [1 0 0 0 1 0 0 0]
 [1 0 1 1 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0]]

Generation:,  5 
 [[0 0 0 0 0 0 1 0]
 [0 0 0 1 1 0 1 0]
 [0 0 0 0 1 0 0 0]
 [0 1 0 0 1 0 0 0]
 [1 0 0 1 0 0 0 1]
 [0 1 0 0 0 0 0 0]
 [0 0 0 

In [28]:
## s=10, p=0.30, t=20
b = conway(10,.30)
advance(b, 20)

Generation:,  0 
 [[0 0 1 0 1 1 0 0 0 0]
 [0 0 1 0 1 0 0 0 1 0]
 [0 0 1 0 1 1 1 1 0 0]
 [0 0 0 0 0 1 1 0 0 0]
 [0 0 0 1 0 1 1 0 0 0]
 [1 1 0 0 0 0 0 0 1 0]
 [0 0 1 1 0 0 0 0 0 0]
 [1 0 1 1 0 0 0 0 1 0]
 [0 0 1 0 1 0 0 1 0 0]
 [0 0 0 0 1 0 0 0 1 0]]

Generation:,  1 
 [[0 0 0 0 1 1 0 0 0 0]
 [0 1 1 0 0 0 0 1 0 0]
 [0 0 0 0 1 0 0 1 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 1 1 1 0 0]
 [0 1 0 1 1 0 0 0 0 0]
 [1 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 1 1 0 1 0 0 1 1 1]
 [0 0 0 0 1 0 0 0 0 0]]

Generation:,  2 
 [[0 0 0 1 1 1 0 0 0 0]
 [0 0 0 1 1 1 1 0 0 0]
 [0 0 1 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 1 0 0]
 [0 0 1 0 0 1 1 0 0 0]
 [0 0 1 1 0 0 1 0 0 0]
 [0 0 1 1 0 0 0 0 0 0]
 [1 1 1 0 1 0 0 0 1 1]
 [0 0 0 0 1 1 0 0 1 0]
 [0 0 0 0 1 0 0 0 1 0]]

Generation:,  3 
 [[0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 1 0 0 1 1 0 0 0]
 [0 0 0 1 1 0 1 0 0 0]
 [0 0 1 0 1 1 1 1 0 0]
 [0 1 0 0 1 1 1 0 0 0]
 [1 0 0 0 1 0 0 0 0 1]
 [1 1 1 0 1 1 0 0 1 1]
 [1 1 0 0 1 1 0 1 1 0]
 [0 0 0 0 0 0 0 0 0 0]]



In [29]:
## s=10, p=0.50, t=10
b = conway(10,.50)
advance(b, 10)

Generation:,  0 
 [[1 1 0 1 1 0 0 1 0 1]
 [1 1 0 1 0 1 1 1 1 0]
 [0 0 0 1 0 1 0 0 1 0]
 [1 1 0 1 0 1 0 0 1 1]
 [1 1 1 1 1 1 0 0 1 0]
 [1 0 1 1 0 1 1 0 1 0]
 [0 1 1 0 0 1 0 1 0 0]
 [0 0 1 1 0 0 0 0 1 0]
 [1 0 0 1 1 0 1 0 0 1]
 [0 1 0 0 1 1 0 0 0 0]]

Generation:,  1 
 [[0 0 0 1 0 0 0 1 0 1]
 [0 1 0 1 0 1 0 0 0 0]
 [0 0 0 1 0 1 0 0 0 0]
 [0 0 0 0 0 1 1 1 1 0]
 [0 0 0 0 0 0 0 0 1 0]
 [1 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 1 0 1 1 1]
 [1 0 0 0 0 1 1 1 1 1]
 [1 1 0 0 0 0 0 0 0 1]
 [0 1 0 0 0 0 1 0 1 0]]

Generation:,  2 
 [[1 0 0 0 1 0 1 1 1 0]
 [0 0 0 1 0 0 1 0 0 0]
 [0 0 1 0 0 1 0 1 0 0]
 [0 0 0 0 1 1 1 1 1 0]
 [0 0 0 0 0 0 1 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 1 0 0 0 1 0 0 0 0]
 [0 1 0 0 0 1 0 0 0 0]
 [0 1 1 0 0 0 0 1 1 0]]

Generation:,  3 
 [[0 1 1 1 0 1 1 0 1 1]
 [0 0 0 1 1 0 0 0 1 0]
 [0 0 0 1 0 0 0 0 1 0]
 [0 0 0 0 1 0 0 0 1 0]
 [0 0 0 0 0 0 1 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 1 0 0 0]
 [1 1 0 0 0 0 1 0 0 0]
 [1 1 1 0 0 1 0 0 1 1]]



In [30]:
## s=15, p=0.50, t=10
b = conway(15,.50)
advance(b, 10)

Generation:,  0 
 [[1 1 1 1 1 0 1 0 1 0 1 1 1 1 0]
 [1 0 1 1 0 1 1 1 1 0 1 1 1 1 1]
 [1 0 1 0 1 1 1 0 0 0 1 1 0 1 0]
 [1 1 0 1 0 0 1 1 1 1 0 0 0 0 1]
 [1 0 1 0 0 0 0 0 1 0 1 0 0 1 0]
 [1 1 1 1 0 0 1 1 0 1 1 1 1 1 1]
 [1 1 0 1 1 0 1 0 1 1 1 1 0 0 1]
 [0 0 0 1 1 0 1 1 0 1 1 0 0 0 1]
 [1 1 1 0 1 1 0 1 1 0 0 1 0 1 0]
 [1 0 0 0 1 1 0 1 1 0 1 0 0 0 1]
 [1 1 0 1 1 0 1 1 1 0 0 0 1 1 1]
 [1 0 0 0 0 0 1 0 1 1 0 1 0 0 0]
 [0 0 1 0 1 0 0 0 0 1 1 1 0 0 0]
 [1 1 0 0 0 1 1 1 1 1 0 0 1 0 0]
 [1 0 0 0 1 1 0 0 0 0 0 1 1 1 0]]

Generation:,  1 
 [[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 1 0 1 0 1 0 0 1 1 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 1 0]
 [0 1 1 0 0 0 0 0 0 0 0 1 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 1 0 1 1 0 0 0 0 0 1 1 1 1 0]
 [1 0 1 0 1 0 1 0 0 0 0 1 0 1 0]
 [1 0 0 0 0 0 0 0 0 0 0 1 1 0 0]
 [1 1 0 1 0 0 1 1 1 1 0 0 0 1 1]
 [0 0

In [31]:
## s=15, p=1.0, t=3
b = conway(15,1.0)
advance(b, 3)

Generation:,  0 
 [[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]

Generation:,  1 
 [[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0

In [32]:
## s=20, p=0.60, t=10
b = conway(20,0.60)
advance(b, 10)

Generation:,  0 
 [[1 1 1 0 1 1 0 1 1 1 0 1 1 0 0 1 1 1 1 1]
 [1 1 0 1 0 0 1 1 0 1 1 1 1 1 1 0 0 1 1 0]
 [1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 0 1 1]
 [0 0 1 1 0 1 1 1 1 1 1 0 1 0 1 1 0 0 1 0]
 [0 0 1 1 1 1 1 1 1 1 0 1 0 0 0 1 1 0 1 0]
 [1 0 0 1 0 0 1 1 0 1 1 1 0 1 0 1 0 1 1 0]
 [1 1 0 0 1 1 0 1 1 1 0 1 1 1 1 1 1 0 0 1]
 [1 0 0 1 0 1 1 0 1 1 1 0 0 1 1 1 1 0 1 1]
 [1 1 0 0 1 1 0 0 1 1 0 1 1 0 1 1 0 0 0 1]
 [1 1 1 1 0 1 1 0 1 1 1 1 1 1 0 0 0 1 0 0]
 [1 0 1 1 0 1 0 1 0 1 1 1 0 1 1 1 1 1 1 0]
 [0 1 1 1 1 0 1 0 1 1 1 0 1 0 0 1 1 1 1 0]
 [1 1 1 0 1 1 1 1 0 1 1 0 1 1 1 0 1 1 0 1]
 [1 0 1 0 0 0 0 0 0 0 1 0 1 1 1 0 1 0 0 0]
 [1 1 1 1 1 0 0 1 0 0 0 1 0 0 1 0 1 1 1 0]
 [1 0 1 1 1 1 1 0 1 1 0 0 1 1 1 0 0 0 0 1]
 [0 1 0 1 1 0 0 0 0 1 1 0 1 1 1 1 0 1 1 0]
 [1 1 1 0 1 0 1 1 0 0 0 1 0 1 1 1 1 1 1 1]
 [1 0 0 0 1 1 0 1 1 1 1 1 1 1 0 1 1 0 1 0]
 [1 1 0 0 1 1 1 1 0 1 1 1 0 1 0 0 0 1 1 0]]

Generation:,  1 
 [[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 

In [34]:
## s=6, p=0.25, t=20
b = conway(6,.25)
advance(b, 5)

Generation:,  0 
 [[0 0 0 0 1 0]
 [0 0 0 0 0 1]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [1 0 0 0 0 1]
 [0 0 0 0 1 1]]

Generation:,  1 
 [[0 0 0 0 1 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 0 0 0 0 1]
 [1 0 0 0 1 0]]

Generation:,  2 
 [[0 0 0 0 0 1]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 0 0 0 0 1]
 [1 0 0 0 1 0]]

Generation:,  3 
 [[0 0 0 0 0 1]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 0 0 0 0 1]
 [1 0 0 0 1 0]]

Generation:,  4 
 [[0 0 0 0 0 1]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 0 0 0 0 1]
 [1 0 0 0 1 0]]

